telefonicaid/fiware-keystone-spassword

docker/postlaunchconfig_update.sh, keystone_spassword/contrib/spassword/backends/sql.py, keystone_spassword/contrib/spassword/controllers.py, keystone_spassword/contrib/spassword/core.py, keystone_spassword/contrib/spassword/routers.py
issue: https://github.com/telefonicaid/fiware-keystone-spassword/issues/20
=> bugfix: add wrapper for delete_user

package-keystone-spassword.sh
Añadida la opcion --with-release para poder pasar a este script la version y release adecuadas desde el jenkins
=> added --with-release option and changed options style

ChangeLog, keystone-spassword.spec, keystone_spassword/contrib/spassword/routers.py, setup.cfg
Fixes: https://github.com/telefonicaid/fiware-keystone-spassword/issues/33
=> fix default path to /OS-SCIM instead of /OS-SCIM/v1

docker/Dockerfile
https://github.com/telefonicaid/fiware-keystone-spassword/issues/42
=> fix URL repo for liberty: now in EOL

ChangeLog, keystone_spassword/contrib/spassword/backends/sql.py, setup.cfg
Issue: https://github.com/telefonicaid/fiware-keystone-spassword/issues/50
=> save last login attempt time

ChangeLog, keystone_spassword/contrib/spassword/mailer.py
Based in PR 79 for master by @cesarjorgemartinez + bumping 1.4.3
=> Fix check configuration for smtp_tls, smtp_user and smtp_password as STMP server connection

README.md, docker/postlaunchconfig.sh, docker/postlaunchconfig_update.sh, docs/DOCKER.md
issue https://github.com/telefonicaid/fiware-keystone-spassword/issues/116
=> add spassword env vars

ChangeLog, README.md, docs/second_factor_auth.md, keystone_spassword/contrib/spassword/controllers.py
https://github.com/telefonicaid/fiware-keystone-spassword/issues/113
=> protect some api methods

ChangeLog, docker/postlaunchconfig.sh, docker/postlaunchconfig_update.sh
fix issue https://github.com/telefonicaid/fiware-keystone-spassword/issues/123
=> add missed list_project_roles keystone permission to policy.json

ChangeLog, docker/Dockerfile, docker/keystone-entrypoint.sh
=> add cron task to flush tokens in docker container (each hour)

docker/Dockerfile
- remove log about:
: ConfigFilesNotFoundError: Failed to find some config files: policy.d
- fix issue https://github.com/telefonicaid/fiware-keystone-spassword/issues/153
- closes Issue/PR https://github.com/telefonicaid/fiware-keystone-spassword/pull/160
=> remove some warning logs

ChangeLog, docker/postlaunchconfig.sh, docker/postlaunchconfig_update.sh
related https://github.com/telefonicaid/fiware-keystone-spassword/issues/199
tmp wsgi is stoppend after startup and then forces keystone-wsgi reads final configuration
=> use temp wsgi for startup

docker/keystone-all, docker/keystone-entrypoint.sh
reopens previous PR
We need wait since process kill has just done before
=> wait before check

docker/postlaunchconfig.sh, docker/postlaunchconfig_update.sh
Reverts telefonicaid/fiware-keystone-spassword#209
=> Revert "provision cep user (when keystone starts without users)"

ChangeLog, docker/postlaunchconfig.sh
https://github.com/telefonicaid/fiware-keystone-spassword/issues/212
=> remove unnecessary drop 

ChangeLog, docker/keystone-entrypoint.sh
Try to detect errors in credentials before try configure docker
=> add check about credentials

ChangeLog, docker/keystone-entrypoint.sh, docker/postlaunchconfig.sh
=> check if db is up even if is behind a load balancer

ChangeLog
It seems this was missing in PR #149
=> FIX changelog

ChangeLog, docker/Dockerfile
=> add openldap clients dep

ChangeLog, docker/postlaunchconfig.sh
=> Support new deployments using mysql 8.0

docs/keystone.smartcity.conf
=> doc about ldapsearch

README.md
https://github.com/telefonicaid/fiware-keystone-spassword/issues/262
=> add procedure for migrate from mysql to postgresql

ChangeLog, README.md, keystone_spassword/contrib/spassword/spassword.py
Issue: https://github.com/telefonicaid/fiware-keystone-spassword/issues/273
=> add reset password procedure
